#Your build pipeline references an undefined variable named ‘PAT’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘branch’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘branch’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- script: |
   git remote add github https://$(PAT)@github.com/KonohaDerek/Notion.SDK.git
   git checkout -b $(branch)
   git push -u github $(branch)
  displayName: 'Command Line Script'